language: node_js
node_js:
  - "6"

before_script:
  - npm install
  - npm install angular-cli@1.0.0-beta.24

script:
  - ng build --environment=prod
  - cp build/. .

deploy:
  - provider: azure_web_apps




  