language: node_js
node_js:
  - "6"

before_script:
  - npm install angular-cli@1.0.0-beta.24

script:
  - ng build --environment=${ngEnvironment}

before_deploy:
  - rm -rf node_modules
  - rm -rf e2e
  - rm -rf scripts
  - cp dist/* .
  - rm -rf dist

deploy:
  skip_cleanup: true
  provider: azure_web_apps




  