language: node_js
node_js:
  - "6"

services:
  - mongodb

before_script:
  - cd API
  - npm install

script:
  - npm test


after_success:
  - cd ..

deploy:
  provider: script
  script: scripts/deploy.sh $GITUSER $GITPASSWORD
  on:
    branch: master



  